name: Node.js CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Test database connection
      - name: Test database connection
        run: |
          echo "Testing database connection..."
          timeout 5 bash -c "echo > /dev/tcp/$(echo $DATABASE_URL | sed -E 's|^.*://[^@]*@([^:/]+).*|\1|')/5432" || exit 2
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Install Backend Dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./smart-asset-tracker-backend

      # Set up Prisma
      - name: Set up Prisma
        run: npx prisma migrate deploy
        working-directory: ./smart-asset-tracker-backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run backend tests
        run: npm test
        working-directory: ./smart-asset-tracker-backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Install and Test Frontend
      - name: Install and test frontend
        working-directory: ./smart-asset-tracker-frontend
        run: |
          npm install
          npm test

      # Build Frontend
      - name: Build frontend
        working-directory: ./smart-asset-tracker-frontend
        run: |
          npm run build

      # Run ESLint
      - name: Run ESLint
        run: npm run lint
        working-directory: ./smart-asset-tracker-backend
